<?php
/**
 * Copyright © Evalent Group AB, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// todo: phpdoc for $block
/** @var \Evalent\EcsterPay\Helper\Data $helper */
$helper = $this->helper(\Evalent\EcsterPay\Helper\Data::class);
// @codingStandardsIgnoreFile
?>
<div id="checkout" data-bind="scope:'checkout'" class="ecsterpay-checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @escapeNotVerified */ __('Loading...') ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?= /* @escapeNotVerified */ $block->getSerializedCheckoutConfig() ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>");
            return url.setBaseUrl('<?= /* @escapeNotVerified */ $block->getBaseUrl() ?>');
        });
        <?php if($helper->isEnabled()): ?>
        require.config({
            map: {
                '*': {
                    'ecsterpayjs':  window.checkoutConfig.payment.ecsterpay.jsUrl
                }
            },
            config : {
                mixins: {
                    'Amasty_StorePickupWithLocator/js/view/pickup/pickup-store': {
                        'Evalent_EcsterPay/js/override/view/pickup/pickup-store': true
                    }
                }
            }
        });
        <?php endif ?>
    </script>
</div>